global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['49.0.40.90:9100']  # Access host metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
