server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3400/loki/api/v1/push


scrape_configs:
  - job_name: system
    decompression:
      enabled: true       # enable decompression
      initial_delay: 10s  # delay before starting to decompress
      format: gz          # decompression format (gz for gzip)
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/**/*.gz   # match compressed log files

